version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  build:
    branches:
      only:
        - main/master
    docker:
      - image: 'cimg/node:16.15.0-browsers'
    steps: 
      - node/install
      - checkout
      - eb/setup
      - aws-cli/install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Frontend install
          command: npm run install:frontend
      - run:
          name: API install
          command: npm run install:api
      - run:
          name: Frontend build
          command: npm run build:frontend-circleci
      - run:
          name: API build
          command: npm run build:api
      # - run:
      #     name: Frontend test
      #     command: npm run test:frontend
      - run: 
          name: API test
          command: npm run test:api
      - run:
          name: Frontend deploy
          command: npm run deploy:frontend
      - run:
          name: API deploy
          command: npm run deploy:api