version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps: 
      - node/install
      - checkout
      - aws-cli/install
      - eb/setup
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: Frontend install
          command: npm run install:frontend
      - run:
          name: API install
          command: npm run install:api
      - run:
          name: Frontend build
          command: npm run build:frontend-circleci
      - run:
          name: API build
          command: npm run build:api
      # - run:
      #     name: Frontend test
      #     command: npm run test:frontend
      - run:
          name: Frontend deploy
          command: npm run deploy:frontend
      - run:
          name: API deploy
          command: npm run deploy:api